### ISSUE TITLE
Multiple databases beyond 100

### ISSUE THREAD

**Issue by kushankurdas** [DozerDB/dozerdb-core#11]
I am running 4.4 versions and able to create upto 100 database but beyond that it throws error
I tried modifying dbms.max_databases to 1000 but its not reflecting 

I am planning to use this project in production hence looking for a immediate solution

**Comment by kushankurdas** [comment]
<img width="984" alt="Screenshot 2024-03-06 at 19 46 28" src="https://github.com/DozerDB/dozerdb-core/assets/90533629/c766dc92-2c90-473f-8b55-400e48209c92">

**Comment by jmsuhy** [comment]
I checked and it is because the max dbs was hard coded to 100.   

We will get that fixed so it honors the dbms.max_databases in both 4.x and 5.x versions.

**Comment by jmsuhy** [comment]
Here is the issue in the MultiDatabaseManager class.
The next push will allow for the configuration option to be set.

```
private void checkDatabaseLimit(NamedDatabaseId namedDatabaseId) {

        // TODO:  Get the actual count from the Graph configuration.
        if (databaseRepository.registeredDatabases().size() >= 100) {
            throw new DatabaseManagementException(
                    "Could not create gdb: " + namedDatabaseId.name() + " because you have exceeded the limit of 100.");
        }
    }
```

**Comment by jmsuhy** [comment]
We need to enforce a minimum of 2 for the default and system database.  So any option > 2 will be acceptable for the first version.

**Comment by kushankurdas** [comment]
Awesome, Let me know if there are ways to contribute to this project, since I am also experimenting with this

**Comment by jmsuhy** [comment]
We updated the 5.x version and will update the 4.x version next.

**Comment by jmsuhy** [comment]
We are focusing on neo4j 5.x moving forward.   This has been fixed in 5.x   
If this is still a need for you, let us know and we can push a patch with an update to the last 4.x release we pushed.

**Comment by dewly-tra** [comment]
This issue is still occurring in version 5x. I tried dbms_max__databases: 1000000 but it did not work.






<img width="529" alt="Screenshot 2024-07-24 at 09 01 47" src="https://github.com/user-attachments/assets/beb28ebe-1019-41ad-9390-e423a3e786a2">

**Comment by dewly-tra** [comment]
Will this issue be reopened?

**Comment by jmsuhy** [comment]
Yes - re-opening the issue.  We will need to create a test for this as well once the issue is identified.  Thank you for letting us know.

**Comment by dewly-tra** [comment]
> Here is the issue in the MultiDatabaseManager class. The next push will allow for the configuration option to be set.
> 
> ```
> private void checkDatabaseLimit(NamedDatabaseId namedDatabaseId) {
> 
>         // TODO:  Get the actual count from the Graph configuration.
>         if (databaseRepository.registeredDatabases().size() >= 100) {
>             throw new DatabaseManagementException(
>                     "Could not create gdb: " + namedDatabaseId.name() + " because you have exceeded the limit of 100.");
>         }
>     }
> ```

It seems like the maxDatabases option setting is being disabled.

![Screenshot 2024-07-24 at 10 57 27](https://github.com/user-attachments/assets/465bc143-20a1-4ba8-a689-7f491effab20)

**Comment by jmsuhy** [comment]
Adding logic to pick up the settings and apply it.

From: https://neo4j.com/docs/operations-manual/current/docker/ref-settings/

Neo4j Config Format: dbms.max_databases 
Docker env format: NEO4J_dbms_max__databases

**Comment by jmsuhy** [comment]
We just released dozerdb for Neo4j Core 5.22.0 - you can now set the max databases in the neo4j.conf or via the docker environment variable.

**Comment by dewly-tra** [comment]
@jmsuhy Thank you so much

**Comment by dewly-tra** [comment]
Hi @jmsuhy 
I still cannot create more than 100 databases, although I have set the environment for Docker and I have also checked the neo4j.conf file in the running container. Everything seems correct, but I still cannot create more than 100 databases.

<img width="797" alt="Screenshot 2024-12-23 at 11 32 18" src="https://github.com/user-attachments/assets/32814654-3b38-4982-8510-cb3ad22deec9" />
<img width="448" alt="Screenshot 2024-12-23 at 11 32 40" src="https://github.com/user-attachments/assets/03c6ad22-4f4b-4e9f-b24a-6291525a4421" />
<img width="1263" alt="Screenshot 2024-12-23 at 11 33 39" src="https://github.com/user-attachments/assets/f1b74625-6636-4579-a585-99b82b8666ee" />

**Comment by dewly-tra** [comment]
Hi @jmsuhy,  

Should this issue be reopened? I have tried many times, but it still doesn't work. I hope this comment reaches you.

**Comment by jmsuhy** [comment]
Can you confirm if you are using DozerDB 4.x or 5.x?

Thank you

**Comment by dewly-tra** [comment]
I am using dozerdb:5.22.0, and I am also trying the dozerdb:5.25.x version.
https://github.com/DozerDB/dozerdb-core/issues/11#issuecomment-2558892551

**Comment by jmsuhy** [comment]
I am going to open this ticket back up - we are working on the 5.26.x LTS release - so this will be part of that release.

**Comment by jmsuhy** [comment]
This should be fixed now in the 5.26.2 LTS release that is coming out this month.    Thanks for pointing it out.   We will close the ticket once the LTS release is pushed.

**Comment by dewly-tra** [comment]
Thank you

**Comment by jmsuhy** [comment]
DozerDB 5.26.3.0 was pushed which should have fixed this issue.
